#!/usr/bin/env bash

# autobuild client
# Copyright (C) 2024 rail5
# Free software (GNU Affero GPL v3)

temporary_log_file=$(mktemp --tmpdir autobuild.log.XXXXXXXXXXXX)

# shellcheck disable=SC2124
passed_options="${@@Q}"

trap 'graceful_exit' INT
trap 'graceful_exit' TERM
trap 'graceful_exit' HUP

function graceful_exit() {
	if [[ -f "$temporary_log_file" ]]; then
		pid_to_kill=$(head -n 1 "$temporary_log_file" | awk '{print $2}')
		touch "/tmp/autobuild.kill.$pid_to_kill"
		tail --pid="$pid_to_kill" -f /dev/null 2>/dev/null
		rm -f "/tmp/autobuild.kill.$pid_to_kill" 2>/dev/null
		rm -f "$temporary_log_file" 2>/dev/null
	fi
        exit 0
}

# getopt
TEMP=$(getopt -o bs --long bell,setup \
              -q -- "$@")

eval set -- "$TEMP"

ring_bell=false

while true; do
	case "$1" in
		-b | --bell )
			ring_bell=true; shift ;;
		-s | --setup )
			if [[ "$(whoami)" != root ]]; then
				echo "-s must be run as root"
				echo "Try again with 'sudo'"
				graceful_exit
			fi
			sudo -u _autobuild autobuild-setup
			graceful_exit ;;
		-- ) shift; break ;;
		* ) break ;;
	esac
done

socat -t 86400 - UNIX-CONNECT:/var/run/autobuild.socket <<<"$passed_options" | tee "$temporary_log_file"

if [[ $ring_bell == true ]]; then
	paplay /usr/share/autobuild/bell.ogg
fi
