#!/usr/bin/env bash

# autobuild client
# Copyright (C) 2024 rail5
# Free software (GNU Affero GPL v3)

temporary_log_file=$(mktemp --tmpdir autobuild.log.XXXXXXXXXXXX)
autobuild_storage_directory="/var/autobuild"

# shellcheck disable=SC2124
passed_options="${@@Q}"

trap 'graceful_exit' INT
trap 'graceful_exit' TERM
trap 'graceful_exit' HUP

function get_daemon_pid() {
	head -n 1 "$temporary_log_file" | awk '{print $2}'
}

function graceful_exit() {
	if [[ -f "$temporary_log_file" ]]; then
		pid_to_kill=$(get_daemon_pid)
		touch "/tmp/autobuild.kill.$pid_to_kill"
		tail --pid="$pid_to_kill" -f /dev/null 2>/dev/null
		rm -f "/tmp/autobuild.kill.$pid_to_kill" 2>/dev/null
		rm -f "$temporary_log_file" 2>/dev/null
	fi
        exit 0
}

# getopt
TEMP=$(getopt -o bo:s --long bell,output:,setup \
              -q -- "$@")

eval set -- "$TEMP"

ring_bell=false
output_directory=$(pwd)

while true; do
	case "$1" in
		-b | --bell )
			ring_bell=true; shift ;;
		-o | --output )
			output_directory=$(realpath "$2")
			shift 2 ;;
		-s | --setup )
			if [[ "$(whoami)" != root ]]; then
				echo "-s must be run as root"
				echo "Try again with 'sudo'"
				graceful_exit
			fi
			sudo -u _autobuild autobuild-setup
			graceful_exit ;;
		-- ) shift; break ;;
		* ) break ;;
	esac
done

# Run the autobuild daemon to build the packages, write the responses to the terminal window and to the temporary log file
socat -t 86400 - UNIX-CONNECT:/var/run/autobuild.socket <<<"$passed_options" | tee "$temporary_log_file"

# Pull the built packages from /var/autobuild/builds and save them in the output directory
cp -r "$autobuild_storage_directory/builds/$(get_daemon_pid)/"* "$output_directory/" 2>/dev/null

# Ask the autobuild daemon to delete the builds from /var/autobuild/builds so we don't waste space
socat - UNIX-CONNECT:/var/run/autobuild.socket <<<"-r $(get_daemon_pid)" >/dev/null

# Ring the bell if the user asked for it
if [[ $ring_bell == true ]]; then
	paplay /usr/share/autobuild/bell.ogg
fi

graceful_exit