# Autobuild configuration

[packages]
package_urls = [
	"https://github.com/rail5/polonius.git",
	"https://github.com/rail5/liesel.git",
	"https://github.com/rail5/bookthief.git",
	"https://github.com/rail5/ocrshot.git",
	"https://github.com/rail5/randomtext.git",
	"https://github.com/rail5/evolution-notify.git",
	"https://github.com/rail5/stepgrampa.git",
	"https://github.com/rail5/autobuild.git",
	"https://github.com/rail5/stranslate.git",
	"https://github.com/rail5/addmake.git"
]

[github]
# Owner username
repo_owner = "rail5"

# Access token
access_token = "github_access_token_here"

git_debian_repo = "https://github.com/rail5/ppa.git"

[forgejo]
# The distribution settings assume that the repository names are the same across github/forgejo/etc

# Location of your forgejo instance
instance_url = "https://git.disroot.org"

# Owner username
repo_owner = "rail5"

# Access token
access_token = "forgejo_access_token_here"
