.\" Manpage for autobuild
.\" Contact andrew@rail5.org to correct errors or typos.
.TH man 8 "12 August 2023" "1.0" "autobuild man page"
.SH NAME
autobuild
.SH SYNOPSIS
autobuild
.SH DESCRIPTION
Autobuild automatically retrieves Debian package sources from Git, builds them, and distributes them.
It can save the built packages locally, distribute them to a GitHub Release Page, and distribute them to a Git-based Debian Repository with reprepro.
.SH OPTIONS
  -p
  --package
    Add a package to the build list

  -1
  --i386
    Build packages on the i386 Build Farm VM
    The i386 VM must have already been built by the setup script (Run 'autobuild -s')

  -2
  --arm64
    Build packages on the arm64 Build Farm VM
    The arm64 VM must have already been built by the setup script (Run 'autobuild -s')

  -o
  --output
    Specify directory to save built package files
    (Default: current directory)

  -d
  --debian-repo
    Distribute built packages to a Git-based Debian Repository managed with reprepro
    This repo must be configured in the CONFIG file

  -g
  --github-page
    Create a Release page on the built packages' Github repositories
    Your GitHub credentials must be present in the CONFIG file

  -s
  --setup
    Run the setup script (after editing your CONFIG file)

  -c
  --config
    Open the CONFIG file for editing

Example:
  autobuild -12dg -p liesel -p bookthief -p polonius
  autobuild --i386 --arm64 --debian-repo --github-page --package liesel --package bookthief --package polonius
  autobuild -p liesel -o ~/Desktop/

If no arguments are provided, the script will run in 'interactive mode'
.SH AUTHOR
rail5 (andrew@rail5.org)
