.\" Manpage for autobuild
.\" Contact andrew@rail5.org to correct errors or typos.
.TH man 8 "1 May 2024" "2.0" "autobuild man page"
.SH NAME
autobuild
.SH SYNOPSIS
autobuild --amd64 --i386 --arm64 -p package-name
.SH DESCRIPTION
Autobuild automatically retrieves Debian package sources from Git, builds them, and distributes them.
It can save the built packages locally, distribute them to a GitHub Release Page, and distribute them to a Git-based Debian Repository with reprepro.
.SH OPTIONS
  -p
  --package
    Add a package to the build list

  -0
  --local
    Build packages on local machine (do not use the Build Farm)

  -1
  --amd64
    Build packages on the amd64 Build Farm VM
    The amd64 VM must have already been built by the setup script (Run 'autobuild -s')

  -2
  --i386
    Build packages on the i386 Build Farm VM
    The i386 VM must have already been built by the setup script (Run 'autobuild -s')

  -3
  --arm64
    Build packages on the arm64 Build Farm VM
    The arm64 VM must have already been built by the setup script (Run 'autobuild -s')

  -o
  --output
    Specify directory to save built package files
    (Default: current working directory)

  -d
  --debian-repo
    Distribute built packages to a Git-based Debian Repository managed with reprepro
    This repo must be configured in the CONFIG file

  -f
  --forgejo-page
    Create release pages for the built packages' Forgejo repositories
    Your Forgejo credentials must be present in the CONFIG file

  -g
  --github-page
    Create release pages for the built packages' Github repositories
    Your GitHub credentials must be present in the CONFIG file

  -b
  --bell
    Ring a bell when finished

  -s
  --setup
    Run the setup script (after editing your CONFIG file)

  -c
  --config
    Open the CONFIG file for editing

  -l
  --list
    List all packages available to build

.SH EXAMPLES
  autobuild -123dg -p package-1 -p package-2

  autobuild --amd64 --i386 --arm64 --debian-repo --github-page --package package-1 --package package-2

  autobuild -0 -p package-1 -o /path/to/save/packages/

  autobuild -c

  autobuild -s

.SH AUTHOR
rail5 (andrew@rail5.org)
